// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVa6NP9zV_nhCxJXCfyUHBEtPMu5E3p64',
    appId: '1:810173979958:web:4dc78bf997e9cfd1ebe797',
    messagingSenderId: '810173979958',
    projectId: 'totalxtask',
    authDomain: 'totalxtask.firebaseapp.com',
    storageBucket: 'totalxtask.appspot.com',
    measurementId: 'G-XBE1GZFY5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_6FC5YgNkOrK6N6TUFh-XtBtJmizUx0',
    appId: '1:810173979958:android:9fd7456178fe299bebe797',
    messagingSenderId: '810173979958',
    projectId: 'totalxtask',
    storageBucket: 'totalxtask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDutIUD45u7YWmHn_OrdM_uerMo5niy2vQ',
    appId: '1:810173979958:ios:fda7e4756d8691dfebe797',
    messagingSenderId: '810173979958',
    projectId: 'totalxtask',
    storageBucket: 'totalxtask.appspot.com',
    iosBundleId: 'com.example.totalxTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDutIUD45u7YWmHn_OrdM_uerMo5niy2vQ',
    appId: '1:810173979958:ios:97e14c12a1f2a8b5ebe797',
    messagingSenderId: '810173979958',
    projectId: 'totalxtask',
    storageBucket: 'totalxtask.appspot.com',
    iosBundleId: 'com.example.totalxTask.RunnerTests',
  );
}
